{% set name = "konfik" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aab64ba3555fc716a27da202f404737d52bc845ec6cb254bc2c0b7c93ec8862d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - konfik = konfik.main:cli_entrypoint

requirements:
  host:
    - python >=3.6
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.6
    - rich >=8.0.0,<9.0.0
    - toml >=0.10.1,<0.11.0
    - python-dotenv >=0.14.0,<0.15.0
    - pyyaml >=5.3.1,<6.0.0

test:
  imports:
    - konfik
  commands:
    - konfik --help

about:
  home: https://github.com/rednafi/konfik
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Strangely Familiar Config Parser
  doc_url: https://github.com/rednafi/konfik
  dev_url: https://github.com/rednafi/konfik

extra:
  recipe-maintainers:
    - carlodri
