{% set name = "konfik" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16b7f82fe77b0afba5ae22876fb6a9cacfae9da277bf0a1ad3b9461828c58c8e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - konfik = konfik:cli_entrypoint

requirements:
  host:
    - python >=3.6
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.6
    - toml >=0.10.2,<0.11.0
    - python-dotenv >=0.15.0,<0.16.0
    - pyyaml >=5.3.1,<6.0.0
    - pygments >=2.7.2,<3.0.0

test:
  imports:
    - konfik
  commands:
    - konfik --help

about:
  home: https://github.com/rednafi/konfik
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Strangely Familiar Config Parser
  doc_url: https://github.com/rednafi/konfik
  dev_url: https://github.com/rednafi/konfik

extra:
  recipe-maintainers:
    - carlodri
